# -*- coding: utf-8 -*-
{
    "name": "BAB Store Scraper",
    "version": "17.0.5.0",
    "summary": "Scraper logs, JSON mapping and Store pricing",
    "category": "Sales/Analysis",
    "author": "Botspot Infoware Pvt. Ltd.",
    "license": "LGPL-3",
    "depends": ["base","product",'sale_subscription','mail'],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
         "demo/scraper_store_1_demo.xml",
        "demo/scraper_store_2_demo.xml",
        "demo/scraper_store_3_demo.xml",
        "demo/scraper_store_4_demo.xml",
        "demo/scraper_store_5_demo.xml",
        "data/sequence.xml",
        "data/ir_cron.xml",

        "views/scraper_store_views.xml",
        "views/scraper_field_mapping_views.xml",
        "views/scraper_request_views.xml",
        "views/scraper_log_views.xml",
        "views/scraped_store_data_views.xml",
        'views/product_product_view.xml',
        'views/store_town.xml',
        'views/ai_config_view.xml',
        'views/company_town_mapping.xml',
        "views/store_town_district.xml",
        "views/error_mail_config_view.xml",
        "views/compititor_town_views.xml",
        "wizard/data_import_wizard.xml",
        "views/menu.xml",
    ],

    "installable": True,
    "application": True,
    "auto_install": False,
}
